#!/bin/bash

if [ ! -f "${HOME}/Desktop/wechat.desktop" ]; then
  cp /usr/share/applications/wechat.desktop "${HOME}/Desktop/"
  cp /usr/share/applications/chromium.desktop "${HOME}/Desktop/"
fi

touch "${HOME}/.config/panel-reload"

wechat --ozone-platform=wayland
